"""Agregando Manejo De Extras

Revision ID: 0d09e6d66692
Revises: bb3d69e69356
Create Date: 2025-03-10 10:56:47.838769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d09e6d66692'
down_revision = 'bb3d69e69356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item_modifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('modification_type', sa.Enum('add', 'remove', 'replace'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('replacement_ingredient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['raw_ingredients.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['replacement_ingredient_id'], ['raw_ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item_modifications')
    # ### end Alembic commands ###
