"""Restrict units to predefined values

Revision ID: 1f6343328f72
Revises: c5a8005b1325
Create Date: 2025-02-24 13:06:07.802719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f6343328f72'
down_revision = 'c5a8005b1325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_ingredients', schema=None) as batch_op:
        batch_op.alter_column('unit',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('kg', 'g', 'l', 'ml', 'piece'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_ingredients', schema=None) as batch_op:
        batch_op.alter_column('unit',
               existing_type=sa.Enum('kg', 'g', 'l', 'ml', 'piece'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
