"""Added mixed ingredient handle

Revision ID: 72133c355c99
Revises: 2067d5c36ec1
Create Date: 2025-02-25 18:53:38.176677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72133c355c99'
down_revision = '2067d5c36ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_ingredients', sa.JSON(), nullable=True))
        batch_op.drop_constraint('order_items_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('order_items_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'menu_items', ['menu_item_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('raw_ingredients', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint('recipes_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('recipes_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'raw_ingredients', ['ingredient_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'menu_items', ['menu_item_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recipes_ibfk_2', 'raw_ingredients', ['ingredient_id'], ['id'])
        batch_op.create_foreign_key('recipes_ibfk_1', 'menu_items', ['menu_item_id'], ['id'])

    with op.batch_alter_table('raw_ingredients', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_items_ibfk_1', 'orders', ['order_id'], ['id'])
        batch_op.create_foreign_key('order_items_ibfk_2', 'menu_items', ['menu_item_id'], ['id'])
        batch_op.drop_column('selected_ingredients')

    # ### end Alembic commands ###
