"""Mejorando SellPoint / GorditaMixta

Revision ID: 952b89ed9f0c
Revises: e377fecaf850
Create Date: 2025-03-14 07:42:24.411381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952b89ed9f0c'
down_revision = 'e377fecaf850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dish_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('dish_type')

    # ### end Alembic commands ###
