"""Add is_active flag to MenuItem for soft deletion

Revision ID: c5a8005b1325
Revises: 3b0a3ed38639
Create Date: 2025-02-24 12:57:58.239021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a8005b1325'
down_revision = '3b0a3ed38639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
