"""MANEJO EXTRAS 2

Revision ID: d69b6b8d44ad
Revises: 0d09e6d66692
Create Date: 2025-03-10 10:59:21.711311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd69b6b8d44ad'
down_revision = '0d09e6d66692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item_modifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_adjustment', sa.Float(), nullable=True))
        batch_op.alter_column('modification_type',
               existing_type=mysql.ENUM('add', 'remove', 'replace'),
               type_=sa.Enum('add', 'remove', 'substitute'),
               existing_nullable=False)
        batch_op.drop_constraint('order_item_modifications_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order_items', ['order_item_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item_modifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_item_modifications_ibfk_2', 'order_items', ['order_item_id'], ['id'])
        batch_op.alter_column('modification_type',
               existing_type=sa.Enum('add', 'remove', 'substitute'),
               type_=mysql.ENUM('add', 'remove', 'replace'),
               existing_nullable=False)
        batch_op.drop_column('price_adjustment')

    # ### end Alembic commands ###
