"""MasCosasParaObjetosEspecialesss

Revision ID: e377fecaf850
Revises: d69b6b8d44ad
Create Date: 2025-03-10 11:26:57.960934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e377fecaf850'
down_revision = 'd69b6b8d44ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('standard_modifications', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('standard_modifications')

    # ### end Alembic commands ###
